### PR TITLE
Components

### PR DESCRIPTION
**Pull request by MiguelHdezP**
Rest of the home task #5

### CODE REVIEW

**Comment by tsunami-dzul** [comment]
Hi Miguel, thanks it looks really good. I think I just have some comments that you can apply to improve your code a little bit:

1. You can simplify App.js moving <main> to a Component.
2. File App.js -> actions() funcitons, it is find just for practice as you mentioned in your comments. I just want to highligh that this function.
will be executed everytime when the component is re-rendered, so if for some reason you decide to keep this functionality you can put that inside
of a useEffect and also you can create a custom hook that could return those functions, so you can keep them as reusable and accesible.
3. I guess Counter is not needed anymore, so probably you can remove it to keep your project clean of unnecessary files.
4. I can see you have different components for buttons like SimpleButon, Button, etc. but in some components you are using the regular button.
(<button>) I think you can homogenize all your project using your button components already created in that way you will have a better control and will take adventage of this funcionality.
5. And related to the functionality I notice that when you click on the MovieCard it display the details (which is the functionality expected) however .
if you make click on another MovieCard it close the previous one but the current one is not displayed, so you need to click again in the MovieCard.
to see the details. I think it would be good if once you make click on another MovieCard it display the details inmediatly, I mean close the previous one and displaying the current one.

Please let me know if you have any question.

**Comment by MiguelHdezP** [comment]
Got it @esdras-dzul, I'll work on that, no question all your comments makes sense, thank you.

**Comment by MiguelHdezP** [comment]
Hi @esdras-dzul.

I have applied the recomendations.

In the case of the different type of buttons, I had 4 type of buttons, I removed SimpleButton, but I kept:
* ActionButton: Which are common buttons with different purposes.
* ButtonIcon: The idea of this type of button is to have a button where an icon can be passed as parameter, and render it to the left or right of the label. 
* CloseButton: Are going to be used only to close things.

Of course this project is not the case but, in a big project where we have lots of close buttons, we have different buttons with different icons (ones with an icon to the left, others with the icon to the right), and also a bunch of different action buttons:
Wouldn't it be good to have the structure and logic separated of each button separated, instead of having a single big button component for all cases?

About the issue with MovieDetails:

> I think it would be good if once you make click on another MovieCard it display the details inmediatly, I mean close the previous one and displaying the current one.

What I did is to load the movie details immediately in the same container, it looks smoother rather than if it is closed  and opened again with the new data. It could be even better if I added a loader icon.

**Comment by tsunami-dzul** [comment]
Hi @MiguelHdezP,

**In the case of the different type of buttons, I had 4 type of buttons, I removed SimpleButton, but I kept:

ActionButton: Which are common buttons with different purposes.
ButtonIcon: The idea of this type of button is to have a button where an icon can be passed as parameter, and render it to the left or right of the label.
CloseButton: Are going to be used only to close things.**

_Thannks for take the adjustments, I think in this way now you have a homegenized buttons all based on you custom buttons._

**Of course this project is not the case but, in a big project where we have lots of close buttons, we have different buttons with different icons (ones with an icon to the left, others with the icon to the right), and also a bunch of different action buttons:
Wouldn't it be good to have the structure and logic separated of each button separated, instead of having a single big button component for all cases?**

_I think you can have both approaches, I mean in some cases maybe it will be enough to have just one button component which will be able to handle all the different cases (Fortunately React is very flexible, you can pass a method a class, content, etc to the component that helps a lot to make a component very polymorphic let's say.), however if some buttons require a more complex behavior then will be good to create a different components for each kind of button, and you can create a complex button structure. In summary it could depend on relation of how complex the button (or any other element) could be, to decide if create a more complex structure or try to manage it on a single component._

By the way you can also use props.children to "pass" the content provided inside of an element, for example currently you are doing this:

```
<button type="button" className="buttonIcon" onClick={click}>
      + {text}
</button>
```

You can also do it like this: 

```
<button type="button" className="buttonIcon" onClick={click}>
      {props.children}
</button>
```

And you can used like:

`<ButtonIcon click={toggleModal}>&#43; Add Movie</Button>`

Also I recoment you to use the HTML code for the symbols instead of the symblols itself, you can fin those symbols in different pages here one of them: https://www.toptal.com/designers/htmlarrows/math/

**About the issue with MovieDetails:
What I did is to load the movie details immediately in the same container, it looks smoother rather than if it is closed and opened again with the new data. It could be even better if I added a loader icon.**

_Thanks, it works great, now once you make click on a different card it is loaded inmediatelly._

Thanks a lot for your adjustments.

**Comment by MiguelHdezP** [comment]
I have used props.children and html codes.

**Pull request merged**
